name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.CONTAINER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        run: |
          # Determine the branch name
          branch=${{ github.ref }}
          if [[ "$branch" == "refs/heads/main" ]]; then
            docker build -t ${{ secrets.CONTAINER_REGISTRY_USERNAME }}/mysql-backup:latest .
            docker push ${{ secrets.CONTAINER_REGISTRY_USERNAME }}/mysql-backup:latest
          elif [[ "$branch" == "refs/heads/dev" ]]; then
            docker build -t ${{ secrets.CONTAINER_REGISTRY_USERNAME }}/mysql-backup:dev .
            docker push ${{ secrets.CONTAINER_REGISTRY_USERNAME }}/mysql-backup:dev
          else
            echo "Skipping Docker image build and push for branch: $branch"
          fi
